=== 98th/java-web-development/module3/src/main/resources/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">

    <complexType name="Gem" abstract="true">
        <sequence>
            <element name="name" type="string" />
            <element name="origin" type="string" />
            <element name="visualParameters" type="tns:VisualParameters" />
            <element name="value" type="double" />
            <element name="date" type="dateTime"/>
        </sequence>
        <attribute name="id" type="int" use="required" />
    </complexType>

    <simpleType name="preciousness">
        <restriction base="string">
            <enumeration value="precious" />
            <enumeration value="semiprecious" />
        </restriction>
    </simpleType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string" />
            <element name="transparency" type="tns:transparency" />
            <element name="facetNum" type="tns:facets"  />
        </sequence>
    </complexType>


    <simpleType name="transparency">
        <restriction base="double">
            <minExclusive value="0" />
            <maxExclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="facets">
        <restriction base="int">
            <minExclusive value="3" />
            <maxExclusive value="16"/>
        </restriction>
    </simpleType>

    <complexType name="SemipreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                 <attribute name="isUsedInOrnamentalWorks" type="boolean" default="false"/>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="PreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                <attribute name="hardness" type="double" use="required"/>
            </extension>
        </complexContent>
    </complexType>


    <element name="gems">
        <complexType>
            <sequence>
                <choice minOccurs="1" maxOccurs="unbounded">
                    <element name="PreciousGem" type="tns:PreciousGem"/>
                    <element name="SemipreciousGem" type="tns:SemipreciousGem"/>
                </choice>
            </sequence>
        </complexType>
    </element>

</schema>

=== 98th/java-web-development/module3/src/test/resources/gems_valid.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">
    <SemipreciousGem id ="1" isUsedInOrnamentalWorks = "true">
        <name>Beryl</name>
        <origin>Bolivia</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>3.0</transparency>
            <facetNum>4</facetNum>
        </visualParameters>
        <value>0.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="2" isUsedInOrnamentalWorks = "true">
        <name>Ametrine</name>
        <origin>Colombia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>2.67</transparency>
            <facetNum>6</facetNum>
        </visualParameters>
        <value>2.0</value>
    </SemipreciousGem>
    <PreciousGem id ="3" hardness = "8.3">
        <name>Emerald</name>
        <origin>Colombia</origin>
        <visualParameters>
            <color>green</color>
            <transparency>25.5</transparency>
            <facetNum>8</facetNum>
        </visualParameters>
        <value>2.5</value>
    </PreciousGem>
    <SemipreciousGem id ="4" isUsedInOrnamentalWorks = "true">
        <name>Sapphire</name>
        <origin>India</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>42.6</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>3.0</value>
    </SemipreciousGem>
    <SemipreciousGem id ="5" isUsedInOrnamentalWorks = "true">
        <name>Andalusite</name>
        <origin>South Africa</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>3.85</transparency>
            <facetNum>14</facetNum>
        </visualParameters>
        <value>3.8</value>
    </SemipreciousGem>
    <PreciousGem id ="6" hardness = "7.5">
        <name>Diaspore</name>
        <origin>Turkey</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>6.8</transparency>
            <facetNum>15</facetNum>
        </visualParameters>
        <value>1.6</value>
    </PreciousGem>
    <SemipreciousGem id ="7" isUsedInOrnamentalWorks = "true">
        <name>Benitoite</name>
        <origin>USA</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>46.8</transparency>
            <facetNum>4</facetNum>
        </visualParameters>
        <value>0.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="8" isUsedInOrnamentalWorks = "false">
        <name>Chrysoberyl</name>
        <origin>Russia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>6.85</transparency>
            <facetNum>6</facetNum>
        </visualParameters>
        <value>2.3</value>
    </SemipreciousGem>
    <PreciousGem id ="9" hardness = "6.5">
        <name>Apatite</name>
        <origin>Russia</origin>
        <visualParameters>
            <color>green</color>
            <transparency>63.52</transparency>
            <facetNum>9</facetNum>
        </visualParameters>
        <value>3.6</value>
    </PreciousGem>
    <SemipreciousGem id ="10" isUsedInOrnamentalWorks = "true">
        <name>Beryl</name>
        <origin>Colombia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>2.67</transparency>
            <facetNum>10</facetNum>
        </visualParameters>
        <value>1.6</value>
    </SemipreciousGem>
    <SemipreciousGem id ="11" isUsedInOrnamentalWorks = "true">
        <name>Rhinestone</name>
        <origin>Colombia</origin>
        <visualParameters>
            <color>white</color>
            <transparency>1.35</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>2.4</value>
    </SemipreciousGem>
    <SemipreciousGem id ="12" isUsedInOrnamentalWorks = "false">
        <name>Jeremejevite</name>
        <origin>Russia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>3.85</transparency>
            <facetNum>13</facetNum>
        </visualParameters>
        <value>1.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="13" isUsedInOrnamentalWorks = "true">
        <name>Garnet</name>
        <origin>Russia</origin>
        <visualParameters>
            <color>red</color>
            <transparency>43.5</transparency>
            <facetNum>8</facetNum>
        </visualParameters>
        <value>1.4</value>
    </SemipreciousGem>
    <PreciousGem id ="14" hardness = "8.6">
        <name>Chrysoberyl</name>
        <origin>Sri Lanka</origin>
        <visualParameters>
            <color>green</color>
            <transparency>1.4</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>2.3</value>
    </PreciousGem>
    <PreciousGem id ="15" hardness = "6.4">
        <name>Diamond</name>
        <origin>Brazil</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>85.2</transparency>
            <facetNum>14</facetNum>
        </visualParameters>
        <value>3.8</value>
    </PreciousGem>
    <SemipreciousGem id ="16" isUsedInOrnamentalWorks = "true">
        <name>Amethyst</name>
        <origin>Germany</origin>
        <visualParameters>
            <color>purple</color>
            <transparency>7</transparency>
            <facetNum>13</facetNum>
        </visualParameters>
        <value>1.5</value>
    </SemipreciousGem>
</gems>

=== 98th/java-web-development/module3/src/test/resources/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">
    <SemipreciousGem id ="1">
        <name>Beryl</name>
        <preciousness>semiprecious</preciousness>
        <origin>Bolivia</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>3.0</transparency>
            <facetNum>4</facetNum>
        </visualParameters>
        <value>0.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="2">
        <name>Ametrine</name>
        <preciousness>semiprecious</preciousness>
        <origin>Colombia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>2.67</transparency>
            <facetNum>6</facetNum>
        </visualParameters>
        <value>2.0</value>
    </SemipreciousGem>
    <PreciousGem id ="3">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Colombia</origin>
        <visualParameters>
            <color>green</color>
            <transparency>25.5</transparency>
            <facetNum>8</facetNum>
        </visualParameters>
        <value>2.5</value>
    </PreciousGem>
    <SemipreciousGem id ="4">
        <name>Sapphire</name>
        <preciousness>semiprecious</preciousness>
        <origin>India</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>42.6</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>3.0</value>
    </SemipreciousGem>
    <SemipreciousGem id ="5">
        <name>Andalusite</name>
        <preciousness>semiprecious</preciousness>
        <origin>South Africa</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>3.85</transparency>
            <facetNum>14</facetNum>
        </visualParameters>
        <value>3.8</value>
    </SemipreciousGem>
    <PreciousGem id ="6">
        <name>Diaspore</name>
        <preciousness>precious</preciousness>
        <origin>Turkey</origin>
        <visualParameters>
            <color>yellow</color>
            <transparency>6.8</transparency>
            <facetNum>15</facetNum>
        </visualParameters>
        <value>1.6</value>
    </PreciousGem>
    <SemipreciousGem id ="7">
        <name>Benitoite</name>
        <preciousness>semiprecious</preciousness>
        <origin>USA</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>46.8</transparency>
            <facetNum>4</facetNum>
        </visualParameters>
        <value>0.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="8">
        <name>Chrysoberyl</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>6.85</transparency>
            <facetNum>6</facetNum>
        </visualParameters>
        <value>2.3</value>
    </SemipreciousGem>
    <PreciousGem id ="9">
        <name>Apatite</name>
        <preciousness>precious</preciousness>
        <origin>Russia</origin>
        <visualParameters>
            <color>green</color>
            <transparency>63.52</transparency>
            <facetNum>9</facetNum>
        </visualParameters>
        <value>3.6</value>
    </PreciousGem>
    <SemipreciousGem id ="10">
        <name>Beryl</name>
        <preciousness>semiprecious</preciousness>
        <origin>Colombia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>2.67</transparency>
            <facetNum>10</facetNum>
        </visualParameters>
        <value>1.6</value>
    </SemipreciousGem>
    <SemipreciousGem id ="11">
        <name>Rhinestone</name>
        <preciousness>semiprecious</preciousness>
        <origin>Colombia</origin>
        <visualParameters>
            <color>white</color>
            <transparency>1.35</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>2.4</value>
    </SemipreciousGem>
    <SemipreciousGem id ="12">
        <name>Jeremejevite</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>3.85</transparency>
            <facetNum>13</facetNum>
        </visualParameters>
        <value>1.8</value>
    </SemipreciousGem>
    <SemipreciousGem id ="13">
        <name>Garnet</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visualParameters>
            <color>red</color>
            <transparency>43.5</transparency>
            <facetNum>8</facetNum>
        </visualParameters>
        <value>1.4</value>
    </SemipreciousGem>
    <PreciousGem id ="14">
        <name>Chrysoberyl</name>
        <preciousness>precious</preciousness>
        <origin>Sri Lanka</origin>
        <visualParameters>
            <color>green</color>
            <transparency>1.4</transparency>
            <facetNum>11</facetNum>
        </visualParameters>
        <value>2.3</value>
    </PreciousGem>
    <PreciousGem id ="15">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Brazil</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>85.2</transparency>
            <facetNum>14</facetNum>
        </visualParameters>
        <value>3.8</value>
    </PreciousGem>
    <SemipreciousGem id ="16">
        <name>Amethyst</name>
        <preciousness>semiprecious</preciousness>
        <origin>Germany</origin>
        <visualParameters>
            <color>purple</color>
            <transparency>7</transparency>
            <facetNum>13</facetNum>
        </visualParameters>
        <value>1.5</value>
    </SemipreciousGem>

</gems>
